version: "3"

services:
  # mosquitto:
  #   image: eclipse-mosquitto
  #   restart: always
  #   ports:
  #     - 1883:1883
  #     - 8883:8883
  #   volumes:
  #     - ./mqtt/data:/mosquitto/data
  #     - ./mqtt/logs:/mosquitto/logs
  #     - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883 
      - 15675:15675
    environment:
      - RABBITMQ_USERNAME= admin
      - RABBITMQ_PASSWORD= admin
    volumes:
      - ./rabbitmq/lib:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 1880:1880
    volumes:
      - node-red-data:/data
    links:
      - rabbitmq
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
  node-red-data:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
