version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/logs:/mosquitto/logs
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf


